export const FETCH_STORIES = 'FETCH_STORIES';
export const FETCH_STORY_DETAILS = 'FETCH_STORY_DETAILS';
export const ADD_STORY = 'ADD_STORY';

export const TOGGLE_NEW_STORY_MODAL = 'TOGGLE_NEW_STORY_MODAL';
export const HANDLE_CHANGE_NEW_STORY_FORM = 'HANDLE_CHANGE_NEW_STORY_FORM';
export const INCREMENT_NEW_STORY_FORM_ID = 'INCREMENT_NEW_STORY_FORM_ID';
